# Numpy

In [2]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3],
              [1, 2, 3]])
a.shape

(2, 3)

In [5]:
a = np.array([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a[0]

1

In [8]:
# slicing
a[1:5]

array([2, 3, 4, 5])

In [9]:
#for dimension
a.ndim

1

In [10]:
# number of elements in a array
a.size

10

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.empty(3)

array([4.24399158e-314, 2.12199579e-314, 6.36598737e-314])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [17]:
b = np.array([1,3,2,4,6,5,6,8,6,8,9,8])

In [18]:
np.sort(b)

array([1, 2, 3, 4, 5, 6, 6, 6, 8, 8, 8, 9])

In [19]:
np.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  3,  2,  4,  6,  5,  6,
        8,  6,  8,  9,  8])

In [23]:
c = np.array([1,2,3,4,5,6,7,8,9,0,10,11,22,33,44,55,66,77,88,99,100])

In [34]:
c.shape

(21,)

In [35]:
print(c<50)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False False False False False False]


In [61]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

s = np.vstack((a,b))
print(s)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [43]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
e = a.copy()

In [45]:
e

array([1, 2, 3, 4, 5])

In [46]:
a.sum()

15

In [47]:
a * 100

array([100, 200, 300, 400, 500])

In [49]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [50]:
a.max()

5

In [51]:
a.min()

1

In [52]:
a.mean()

3.0

In [53]:
a +  b

array([ 7,  9, 11, 13, 15])

In [54]:
a - b

array([-5, -5, -5, -5, -5])

In [55]:
a * b

array([ 6, 14, 24, 36, 50])

In [56]:
a / b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [58]:
f = np.array([1,2,2,2,3,4,5,6,7,8,99,7,6,5,43,2])

In [59]:
np.unique(f)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 43, 99])

In [63]:
print(s)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [64]:
s.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [65]:
s.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [66]:
# array get reversed
np.flip(s)

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [67]:
# make your array into 1D array
g = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] , [13, 14, 15, 16]])
g.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [68]:
s

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [69]:
# make your array into 1D array
s.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
help(min)

Help on built-in function min in module builtins:

min(...)
    min(iterable, *[, default=obj, key=func]) -> value
    min(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its smallest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the smallest argument.



# Pandas

In [76]:
import pandas as pd

In [80]:
pd.DataFrame({'A': [1, 2, 3]})

A
0  1
1  2
2  3

In [85]:
s = pd.Series([1,2,3,4,5,6,7,np.nan])
s

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
7    NaN
dtype: float64

In [94]:
date = pd.date_range("20240401", periods=10)
date

DatetimeIndex(['2024-04-01', '2024-04-02', '2024-04-03', '2024-04-04',
               '2024-04-05', '2024-04-06', '2024-04-07', '2024-04-08',
               '2024-04-09', '2024-04-10'],
              dtype='datetime64[ns]', freq='D')

In [99]:
df = pd.DataFrame(np.random.randn(10, 4), index=date, columns=list("ABCD"))

In [100]:
df

A         B         C         D
2024-04-01  0.294547  0.098186  1.069532 -0.544626
2024-04-02 -0.236064 -0.046320 -0.656822 -1.335055
2024-04-03 -1.169434 -0.200888  2.649257 -1.600009
2024-04-04 -0.615174 -0.008988 -0.416590 -1.368853
2024-04-05 -1.736736 -1.198327  0.405947 -0.895075
2024-04-06 -1.163557 -2.232601  1.421231 -0.307724
2024-04-07 -0.604983 -1.095105 -0.752102 -1.017102
2024-04-08 -0.191559 -0.507523 -0.605789  0.119537
2024-04-09  1.051745 -0.317009  0.928733  0.958397
2024-04-10 -1.886873  0.404516  0.210867 -0.606436

In [101]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20240401"),
        "C": pd.Series(4, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "food",
    }
)


In [102]:
df2

A          B    C  D      E     F
0  1.0 2024-04-01  4.0  3   test  food
1  1.0 2024-04-01  4.0  3  train  food
2  1.0 2024-04-01  4.0  3   test  food
3  1.0 2024-04-01  4.0  3  train  food

In [104]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [107]:
df.head(5)

A         B         C         D
2024-04-01  0.294547  0.098186  1.069532 -0.544626
2024-04-02 -0.236064 -0.046320 -0.656822 -1.335055
2024-04-03 -1.169434 -0.200888  2.649257 -1.600009
2024-04-04 -0.615174 -0.008988 -0.416590 -1.368853
2024-04-05 -1.736736 -1.198327  0.405947 -0.895075

In [108]:
df.tail(5)

A         B         C         D
2024-04-06 -1.163557 -2.232601  1.421231 -0.307724
2024-04-07 -0.604983 -1.095105 -0.752102 -1.017102
2024-04-08 -0.191559 -0.507523 -0.605789  0.119537
2024-04-09  1.051745 -0.317009  0.928733  0.958397
2024-04-10 -1.886873  0.404516  0.210867 -0.606436

In [109]:
df.index

DatetimeIndex(['2024-04-01', '2024-04-02', '2024-04-03', '2024-04-04',
               '2024-04-05', '2024-04-06', '2024-04-07', '2024-04-08',
               '2024-04-09', '2024-04-10'],
              dtype='datetime64[ns]', freq='D')

In [110]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [111]:
# for numpy representation or showing the data without the labels (index and columns)
df.to_numpy()

array([[ 0.29454688,  0.09818634,  1.06953153, -0.54462559],
       [-0.23606412, -0.04631966, -0.6568216 , -1.33505454],
       [-1.16943358, -0.20088844,  2.64925733, -1.60000925],
       [-0.61517376, -0.00898819, -0.4165902 , -1.36885322],
       [-1.73673647, -1.19832676,  0.4059474 , -0.89507451],
       [-1.16355673, -2.23260136,  1.42123109, -0.30772392],
       [-0.60498274, -1.09510532, -0.75210237, -1.01710186],
       [-0.19155874, -0.50752335, -0.60578871,  0.11953732],
       [ 1.05174469, -0.31700876,  0.92873259,  0.95839744],
       [-1.8868728 ,  0.4045156 ,  0.21086672, -0.60643591]])

In [112]:
df2.to_numpy()

array([[1.0, Timestamp('2024-04-01 00:00:00'), 4.0, 3, 'test', 'food'],
       [1.0, Timestamp('2024-04-01 00:00:00'), 4.0, 3, 'train', 'food'],
       [1.0, Timestamp('2024-04-01 00:00:00'), 4.0, 3, 'test', 'food'],
       [1.0, Timestamp('2024-04-01 00:00:00'), 4.0, 3, 'train', 'food']],
      dtype=object)

In [114]:
# describe() used for summary
df.describe()

A                    B    C    D
count  4.0                    4  4.0  4.0
mean   1.0  2024-04-01 00:00:00  4.0  3.0
min    1.0  2024-04-01 00:00:00  4.0  3.0
25%    1.0  2024-04-01 00:00:00  4.0  3.0
50%    1.0  2024-04-01 00:00:00  4.0  3.0
75%    1.0  2024-04-01 00:00:00  4.0  3.0
max    1.0  2024-04-01 00:00:00  4.0  3.0
std    0.0                  NaN  0.0  0.0

In [116]:
# .T used for transpose
df.T

2024-04-01  2024-04-02  2024-04-03  2024-04-04  2024-04-05  2024-04-06  \
A    0.294547   -0.236064   -1.169434   -0.615174   -1.736736   -1.163557   
B    0.098186   -0.046320   -0.200888   -0.008988   -1.198327   -2.232601   
C    1.069532   -0.656822    2.649257   -0.416590    0.405947    1.421231   
D   -0.544626   -1.335055   -1.600009   -1.368853   -0.895075   -0.307724   

   2024-04-07  2024-04-08  2024-04-09  2024-04-10  
A   -0.604983   -0.191559    1.051745   -1.886873  
B   -1.095105   -0.507523   -0.317009    0.404516  
C   -0.752102   -0.605789    0.928733    0.210867  
D   -1.017102    0.119537    0.958397   -0.606436

In [118]:
df.sort_index(axis = 1 ,ascending = False)

D         C         B         A
2024-04-01 -0.544626  1.069532  0.098186  0.294547
2024-04-02 -1.335055 -0.656822 -0.046320 -0.236064
2024-04-03 -1.600009  2.649257 -0.200888 -1.169434
2024-04-04 -1.368853 -0.416590 -0.008988 -0.615174
2024-04-05 -0.895075  0.405947 -1.198327 -1.736736
2024-04-06 -0.307724  1.421231 -2.232601 -1.163557
2024-04-07 -1.017102 -0.752102 -1.095105 -0.604983
2024-04-08  0.119537 -0.605789 -0.507523 -0.191559
2024-04-09  0.958397  0.928733 -0.317009  1.051745
2024-04-10 -0.606436  0.210867  0.404516 -1.886873

In [120]:
df.sort_values(by = "A")

A         B         C         D
2024-04-10 -1.886873  0.404516  0.210867 -0.606436
2024-04-05 -1.736736 -1.198327  0.405947 -0.895075
2024-04-03 -1.169434 -0.200888  2.649257 -1.600009
2024-04-06 -1.163557 -2.232601  1.421231 -0.307724
2024-04-04 -0.615174 -0.008988 -0.416590 -1.368853
2024-04-07 -0.604983 -1.095105 -0.752102 -1.017102
2024-04-02 -0.236064 -0.046320 -0.656822 -1.335055
2024-04-08 -0.191559 -0.507523 -0.605789  0.119537
2024-04-01  0.294547  0.098186  1.069532 -0.544626
2024-04-09  1.051745 -0.317009  0.928733  0.958397

In [121]:
df.iloc[:,:-1]

A         B         C
2024-04-01  0.294547  0.098186  1.069532
2024-04-02 -0.236064 -0.046320 -0.656822
2024-04-03 -1.169434 -0.200888  2.649257
2024-04-04 -0.615174 -0.008988 -0.416590
2024-04-05 -1.736736 -1.198327  0.405947
2024-04-06 -1.163557 -2.232601  1.421231
2024-04-07 -0.604983 -1.095105 -0.752102
2024-04-08 -0.191559 -0.507523 -0.605789
2024-04-09  1.051745 -0.317009  0.928733
2024-04-10 -1.886873  0.404516  0.210867

In [124]:
df.iloc[:,-1:]

D
2024-04-01 -0.544626
2024-04-02 -1.335055
2024-04-03 -1.600009
2024-04-04 -1.368853
2024-04-05 -0.895075
2024-04-06 -0.307724
2024-04-07 -1.017102
2024-04-08  0.119537
2024-04-09  0.958397
2024-04-10 -0.606436

In [125]:
z = df.copy()

In [126]:
z

A         B         C         D
2024-04-01  0.294547  0.098186  1.069532 -0.544626
2024-04-02 -0.236064 -0.046320 -0.656822 -1.335055
2024-04-03 -1.169434 -0.200888  2.649257 -1.600009
2024-04-04 -0.615174 -0.008988 -0.416590 -1.368853
2024-04-05 -1.736736 -1.198327  0.405947 -0.895075
2024-04-06 -1.163557 -2.232601  1.421231 -0.307724
2024-04-07 -0.604983 -1.095105 -0.752102 -1.017102
2024-04-08 -0.191559 -0.507523 -0.605789  0.119537
2024-04-09  1.051745 -0.317009  0.928733  0.958397
2024-04-10 -1.886873  0.404516  0.210867 -0.606436

In [127]:
df.mean()

A   -0.625809
B   -0.510406
C    0.425426
D   -0.659694
dtype: float64

In [129]:
df * 1000

A            B            C            D
2024-04-01   294.546879    98.186345  1069.531529  -544.625593
2024-04-02  -236.064123   -46.319658  -656.821600 -1335.054537
2024-04-03 -1169.433581  -200.888436  2649.257326 -1600.009248
2024-04-04  -615.173763    -8.988193  -416.590198 -1368.853216
2024-04-05 -1736.736473 -1198.326763   405.947402  -895.074505
2024-04-06 -1163.556730 -2232.601360  1421.231091  -307.723921
2024-04-07  -604.982741 -1095.105324  -752.102365 -1017.101861
2024-04-08  -191.558736  -507.523347  -605.788710   119.537317
2024-04-09  1051.744686  -317.008763   928.732592   958.397438
2024-04-10 -1886.872799   404.515598   210.866722  -606.435914

In [130]:
df + 100000

A              B              C              D
2024-04-01  100000.294547  100000.098186  100001.069532   99999.455374
2024-04-02   99999.763936   99999.953680   99999.343178   99998.664945
2024-04-03   99998.830566   99999.799112  100002.649257   99998.399991
2024-04-04   99999.384826   99999.991012   99999.583410   99998.631147
2024-04-05   99998.263264   99998.801673  100000.405947   99999.104925
2024-04-06   99998.836443   99997.767399  100001.421231   99999.692276
2024-04-07   99999.395017   99998.904895   99999.247898   99998.982898
2024-04-08   99999.808441   99999.492477   99999.394211  100000.119537
2024-04-09  100001.051745   99999.682991  100000.928733  100000.958397
2024-04-10   99998.113127  100000.404516  100000.210867   99999.393564

In [131]:
df / 1000

A         B         C         D
2024-04-01  0.000295  0.000098  0.001070 -0.000545
2024-04-02 -0.000236 -0.000046 -0.000657 -0.001335
2024-04-03 -0.001169 -0.000201  0.002649 -0.001600
2024-04-04 -0.000615 -0.000009 -0.000417 -0.001369
2024-04-05 -0.001737 -0.001198  0.000406 -0.000895
2024-04-06 -0.001164 -0.002233  0.001421 -0.000308
2024-04-07 -0.000605 -0.001095 -0.000752 -0.001017
2024-04-08 -0.000192 -0.000508 -0.000606  0.000120
2024-04-09  0.001052 -0.000317  0.000929  0.000958
2024-04-10 -0.001887  0.000405  0.000211 -0.000606

In [134]:
df2

A          B    C  D      E     F
0  1.0 2024-04-01  4.0  3   test  food
1  1.0 2024-04-01  4.0  3  train  food
2  1.0 2024-04-01  4.0  3   test  food
3  1.0 2024-04-01  4.0  3  train  food

# Matplotlib

In [136]:
import matplotlib.pyplot as plt